const MEDIA_TYPE_HEADERS: [[&[u8]; 2]; 18] = [
    // Image
    [b"GIF87a", b"image/gif"],
    [b"GIF89a", b"image/gif"],
    [b"\xFF\xD8\xFF", b"image/jpeg"],
    [b"\x89PNG\x0D\x0A\x1A\x0A", b"image/png"],
    [b"<svg ", b"image/svg+xml"],
    [b"RIFF....WEBPVP8 ", b"image/webp"],
    [b"\x00\x00\x01\x00", b"image/x-icon"],
    // Audio
    [b"ID3", b"audio/mpeg"],
    [b"\xFF\x0E", b"audio/mpeg"],
    [b"\xFF\x0F", b"audio/mpeg"],
    [b"OggS", b"audio/ogg"],
    [b"RIFF....WAVEfmt ", b"audio/wav"],
    [b"fLaC", b"audio/x-flac"],
    // Video
    [b"RIFF....AVI LIST", b"video/avi"],
    [b"....ftyp", b"video/mp4"],
    [b"\x00\x00\x01\x0B", b"video/mpeg"],
    [b"....moov", b"video/quicktime"],
    [b"\x1A\x45\xDF\xA3", b"video/webm"],
];

// "avi" => "video/avi",
// "bmp" => "image/bmp",
// "css" => "text/css",
// "flac" => "audio/flac",
// "gif" => "image/gif",
// "htm" | "html" => "text/html",
// "ico" => "image/x-icon",
// "jpeg" | "jpg" => "image/jpeg",
// "js" => "application/javascript",
// "json" => "application/json",
// "mp3" => "audio/mpeg",
// "mp4" | "m4v" => "video/mp4",
// "ogg" => "audio/ogg",
// "ogv" => "video/ogg",
// "pdf" => "application/pdf",
// "png" => "image/png",
// "svg" => "image/svg+xml",
// "swf" => "application/x-shockwave-flash",
// "tif" | "tiff" => "image/tiff",
// "txt" => "text/plain",
// "wav" => "audio/wav",
// "webp" => "image/webp",
// "woff" => "font/woff",
// "woff2" => "font/woff2",
// "xml" => "text/xml",
